### ISSUE TITLE
怎么使用 ELK Stack 监控 日志.

### ISSUE THREAD

**Issue by alvin2ye** [alvin2ye/blog#2]
# 怎么使用 ELK Stack 集中管理日志

目地:
- 集中存储: 不会丢, 找得快
- 搜索方便
- 报表方便

通过搜索, 发现 ELK Stack 是普遍方案, 同时又可以用docker跑.

ELK Stack 是 Elasticsearch、Logstash、Kibana 三个开源软件的组合。在实时数据检索和分析场合，三者通常是配合共用，而且又都先后归于 Elastic.co 公司名下，故有此简称。
1. Ruby with docker
   
   > docker run -it --rm -p 5601:5601 -p 9200:9200 -p 5044:5044 -p 5000:5000 --name elk sebp/elk
2. 进入 container, 复制 /usr/local/etc/ssl/certs/logstash-beats.crt 到客户端
3. 配置 filebeat.yml
   
   ```
   filebeat: 
   prospectors: 
     - 
       document_type: nginx-access
       paths: 
         - nginx-access.log
   output: 
   logstash: 
     enabled: true
     hosts: 
       - "localhost:5044"
     tls: 
       certificate_authorities: 
         - logstash-beats.crt
   ```
4. Run
   
   > filebeat -v -e

REF: 
- https://elk-docker.readthedocs.io/#security-considerations
- ELKstack 中文指南 https://www.gitbook.com/book/chenryn/kibana-guide-cn/details
- https://github.com/spujadas/elk-docker/issues/24
