### ISSUE TITLE
docker-compose wordpress

### ISSUE THREAD

**Issue by alvin2ye** [alvin2ye/blog#5]
```
version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 10500:80
    environment:
      WORDPRESS_DB_PASSWORD: password

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
```
