### ISSUE TITLE
教学: 如何用Docker开发 rails + react 的项目笔记

### ISSUE THREAD

**Issue by alvin2ye** [alvin2ye/blog#7]
vi docker-compose.yml

```
version: "2"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./mnt:/mnt"

  redis:
    image: redis:3.2-alpine
    volumes:
      - "redis-data:/data"
      - "./mnt:/mnt"
  main:
    image: ubuntu
    hostname: check_me-dev
    ports:
      - "10980:8080"
      - "10900:3000"
    volumes:
      - ".:/app"
      - "/Users/alvin/.ssh/id_rsa:/root/.ssh/id_rsa"
      - "./mnt:/mnt"
    environment:
      - DOCKER_ENV=development
    depends_on:
      - redis
      - mysql
volumes:
  mysql-data:
  redis-data:

```

```
gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/
bundle config mirror.https://rubygems.org https://gems.ruby-china.org
gem install rails
export PATH=/usr/local/node/bin:/usr/local/bundle/bin:$PATH
cd /app
rails new .
rails g scaffold book name:string
rails g controller home index
mkdir frontend
cd frontend
npm config set registry https://registry.npm.taobao.org 
npm info underscore
npm install -g create-react-app
create-react-app .
PORT=8080 HOST=0.0.0.0 npm run start
http://aa.docker.do8.cc:10980/static/js/bundle.js

```
